= RESTEasy MicroProfile Reference Guide
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

== Introduction

The RESTEasy MicroProfile project provides implementations for https://microprofile.io/[Eclipse MicroProfile] specifications that integrate with RESTEasy.

This guide covers the following components:

* **MicroProfile REST Client** - Implementation of the https://download.eclipse.org/microprofile/microprofile-rest-client-4.0/microprofile-rest-client-spec-4.0.html[MicroProfile REST Client] specification
* **MicroProfile Config** - Integration with https://download.eclipse.org/microprofile/microprofile-config-3.1/microprofile-config-spec-3.1.html[MicroProfile Config]
* **MicroProfile Context Propagation** - Support for https://download.eclipse.org/microprofile/microprofile-context-propagation-1.0/microprofile-context-propagation.html[MicroProfile Context Propagation]

=== Version Information

This guide is for RESTEasy MicroProfile version {resteasy-mp-version}.

For the main RESTEasy documentation (Jakarta REST implementation), see https://docs.resteasy.dev/resteasy[docs.resteasy.dev/resteasy].

== Getting Started

=== Maven Dependencies

The simplest way to use these dependencies is to import the BOM:

[source,xml,subs="attributes+"]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.jboss.resteasy.microprofile</groupId>
            <artifactId>resteasy-microprofile-bom</artifactId>
            <version>{resteasy-mp-version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

Then add the specific components you need:

[source,xml]
----
<!-- MicroProfile REST Client -->
<dependency>
    <groupId>org.jboss.resteasy.microprofile</groupId>
    <artifactId>microprofile-rest-client</artifactId>
</dependency>

<!-- MicroProfile Config Integration -->
<dependency>
    <groupId>org.jboss.resteasy.microprofile</groupId>
    <artifactId>microprofile-config</artifactId>
</dependency>

<!-- MicroProfile Context Propagation -->
<dependency>
    <groupId>org.jboss.resteasy.microprofile</groupId>
    <artifactId>microprofile-context-propagation</artifactId>
</dependency>
----

=== WildFly Installation

The MicroProfile REST Client implementation and MicroProfile Config sources are already provided in WildFly.
If you'd like to upgrade or add all the modules to a provisioned WildFly server, you can use the
https://docs.wildfly.org/galleon/[Galleon] tooling.

==== Using the WildFly Maven Plugin

[source,xml,subs="attributes+"]
----
<plugin>
    <groupId>org.wildfly.plugins</groupId>
    <artifactId>wildfly-maven-plugin</artifactId>
    <configuration>
        <provisioning-dir>${jboss.home}</provisioning-dir>
        <galleon-options>
            <jboss-fork-embedded>true</jboss-fork-embedded>
            <jboss-maven-dist/>
        </galleon-options>
        <feature-packs>
            <feature-pack>
                <groupId>org.wildfly</groupId>
                <artifactId>wildfly-galleon-pack</artifactId>
            </feature-pack>
        </feature-packs>
        <channels>
            <channel>
                <manifest>
                    <groupId>org.wildfly</groupId>
                    <artifactId>wildfly</artifactId>
                </manifest>
            </channel>
            <!-- Optional: Get the latest version of RESTEasy -->
            <channel>
                <manifest>
                    <groupId>org.jboss.resteasy.channels</groupId>
                    <artifactId>resteasy-6.2</artifactId>
                </manifest>
            </channel>
            <channel>
                <manifest>
                    <groupId>org.jboss.resteasy.channels</groupId>
                    <artifactId>resteasy-microprofile-{channel-stream-version}</artifactId>
                </manifest>
            </channel>
        </channels>
        <layers>
            <layer>cdi</layer>
            <layer>jaxrs-server</layer>
            <layer>microprofile-config</layer>
        </layers>
    </configuration>
</plugin>
----

include::rest_client.adoc[]

include::config.adoc[]

include::context_propagation.adoc[]
